program: src/LDS_test.py
method: bayes
metric:
  goal: minimize
  name: cost
parameters:
  model.kernel_lscale:
    values: [0.1, 0.5, 1.0, 3.0, 10.0, 15.0, 20.0, 30.0]
  model.kernel_sigma:
    values: [0.1, 0.5, 1.0, 3.0, 10.0, 15.0, 20.0, 30.0]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
